Hook race fix
stackhpc/slurm-k8s-cluster pull request #21
Opened 2023-08-08 11:54 UTC by wtripp180901

The pre-upgrade hook will now drain all nodes before checking if jobs are running on them in order to prevent a race conditions in which pending jobs are scheduled onto the nodes after the check if complete. Will RESUME nodes on a successful upgrade

2023-08-08 13:16 UTC, sjpb requested changes

2023-08-08 13:16 UTC, sjpb commented on docker-entrypoint.sh
> +    ALL_NODES=$( sinfo --Node --noheader --Format=NodeList )
This block of changes can just be replaced with:

`scontrol update NodeName=all ...`

2023-08-08 13:16 UTC, sjpb commented on docker-entrypoint.sh
> +            for i in $ALL_NODES
See above re "NodeName=all"

2023-08-08 13:16 UTC, sjpb commented on docker-entrypoint.sh
> +                    scontrol update NodeName=$i State=RESUME
My worry about RESUME is that if a node is genuinely down, then this will (possibly temporarily) reset it. Can you try this with UNDRAIN instead please and see if the jobs runs in this case:

```
# cd /home/rocky # else we won't get job output anyway
# scontrol update nodename=all state=down reason=test
# sbatch -N2 --wrap "srun hostname"
# squeue # should queue cause nodes are down
# scontrol update nodename=all state=undrain


Is the undrain here sufficent to let the job run? Or not? With an autoscaling cluster is is, but that might be different.

2023-08-08 14:11 UTC, wtripp180901 commented on docker-entrypoint.sh
> +                    scontrol update NodeName=$i State=RESUME
Interestingly if you set the nodes to down and then schedule a job the nodes will go back up and it will run anyway. I tried putting them into the fail state and then undraining them and the job ran, both with undrain and resume

2023-08-08 14:21 UTC, wtripp180901 commented
Made scontrol changes, only thing is that by using NodeName=all the other named nodes (i.e slurmd-[2-9]) will get added to the list in a drain state, but I'm guessing this wouldn't really be an issue in production?

2023-08-08 14:51 UTC, wtripp180901 commented
Actually one thing that I've realised is that this fix introduces a NEW race condition where once the nodes are undrained, jobs could potentially get scheduled onto them before the upgrade starts, I need to move the undraining to a post-upgrade hook

2023-08-18 13:57 UTC, sjpb approved these changes

2023-08-18 14:07 UTC, merged